"""Tokenizer-corpus filtering and deterministic quota selection for Brittain3."""
from __future__ import annotations

import hashlib
import json
import os
import random
import re
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable, Iterator


CODE_EXTENSIONS = {
    ".py": "python", ".pyi": "python",
    ".js": "javascript", ".jsx": "javascript",
    ".ts": "typescript", ".tsx": "typescript",
    ".c": "c_cpp", ".h": "c_cpp", ".cc": "c_cpp", ".cpp": "c_cpp",
    ".cxx": "c_cpp", ".hpp": "c_cpp",
    ".rs": "rust", ".go": "go",
    ".java": "java_kotlin", ".kt": "java_kotlin", ".kts": "java_kotlin",
    ".sh": "shell", ".bash": "shell", ".zsh": "shell", ".fish": "shell",
    ".ps1": "shell", ".psm1": "shell",
    ".rb": "other", ".php": "other", ".swift": "other", ".lua": "other",
    ".r": "other", ".scala": "other", ".ex": "other", ".exs": "other",
}
DOCUMENTATION_EXTENSIONS = {".md", ".mdx", ".rst", ".adoc", ".txt"}
STRUCTURED_EXTENSIONS = {
    ".json", ".jsonl", ".yaml", ".yml", ".toml", ".xml", ".ini", ".cfg",
    ".conf", ".properties", ".sql", ".graphql", ".proto", ".css", ".scss",
    ".html", ".htm", ".vue", ".svelte", ".ipynb",
}
STRUCTURED_NAMES = {
    "dockerfile", "makefile", "cmakelists.txt", "justfile", "procfile",
    "package.json", "tsconfig.json", "pyproject.toml", "cargo.toml", "go.mod",
}
SKIP_PARTS = {
    ".git", ".hg", ".svn", "node_modules", "vendor", "vendors", "dist", "build",
    "coverage", ".next", ".nuxt", "target", "__pycache__", ".venv", "venv",
    "third_party", "third-party", "generated", ".cache", "data", "runs",
    "checkpoints", "benchmarks", "artifacts", "tokenizers",
    "benchmark", ".codex-build", ".pytest_cache", ".mypy_cache", ".ruff_cache",
    ".tox", "site", "release-assets", ".claude", ".vscode",
}
SKIP_NAMES = {
    "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "poetry.lock", "cargo.lock",
    "composer.lock", "go.sum",
}
SECRET_PATTERNS = (
    re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"),
    re.compile(r"\bgh[opsu]_[A-Za-z0-9]{30,}\b"),
    re.compile(r"\bAKIA[0-9A-Z]{16}\b"),
    re.compile(r"\bsk-[A-Za-z0-9_-]{24,}\b"),
)
GENERATED_MARKERS = (
    "@generated", "code generated", "automatically generated", "do not edit",
    "generated by", "this file was generated",
)


def normalize_language(value: str | None) -> str:
    low = (value or "other").strip().lower().replace(" ", "_").replace("-", "_")
    aliases = {
        "python": "python", "javascript": "javascript", "jsx": "javascript",
        "typescript": "typescript", "tsx": "typescript",
        "c": "c_cpp", "c++": "c_cpp", "cpp": "c_cpp", "c_cpp": "c_cpp",
        "rust": "rust", "go": "go", "golang": "go",
        "java": "java_kotlin", "kotlin": "java_kotlin", "java_kotlin": "java_kotlin",
        "shell": "shell", "bash": "shell", "powershell": "shell",
    }
    return aliases.get(low, "other")


def accepted_license(values, allowed: set[str]) -> str | None:
    if isinstance(values, str):
        values = [values]
    aliases = {value.lower(): value for value in allowed}
    aliases.update({
        "apache-2.0": "Apache-2.0", "apache-2": "Apache-2.0",
        "bsd-2-clause": "BSD-2-Clause", "bsd-3-clause": "BSD-3-Clause",
        "cc0-1.0": "CC0-1.0", "unlicense": "Unlicense",
    })
    licenses = [aliases.get(str(value).lower(), str(value)) for value in (values or []) if value]
    if not licenses or any(value not in allowed for value in licenses):
        return None
    return sorted(licenses)[0]


def stack_v1_provenance(row: dict, allowed: set[str]) -> tuple[str, str, str] | None:
    """Select one licensed repository location from a deduplicated Stack row."""
    direct = accepted_license(row.get("licenses"), allowed)
    if direct:
        return (
            direct,
            str(row.get("repository_name") or row.get("hexsha") or "unknown"),
            str(row.get("path") or f"unknown.{row.get('ext') or 'txt'}"),
        )
    for prefix in ("max_stars", "max_forks", "max_issues"):
        license_name = accepted_license(row.get(f"{prefix}_repo_licenses"), allowed)
        if license_name:
            return (
                license_name,
                str(row.get(f"{prefix}_repo_name") or row.get("hexsha") or "unknown"),
                str(row.get(f"{prefix}_repo_path") or f"unknown.{row.get('ext') or 'txt'}"),
            )
    return None


def classify_path(path: str) -> tuple[str | None, str]:
    candidate = Path(path)
    name = candidate.name.lower()
    suffix = candidate.suffix.lower()
    if name in STRUCTURED_NAMES or suffix in STRUCTURED_EXTENSIONS:
        return "structured", normalize_language(suffix.removeprefix("."))
    if suffix in DOCUMENTATION_EXTENSIONS or name.startswith(("readme", "changelog")):
        return "documentation", "english"
    if suffix in CODE_EXTENSIONS:
        return "code", CODE_EXTENSIONS[suffix]
    return None, "other"


def stable_order(paths: Iterable[Path], seed: int) -> list[Path]:
    return sorted(
        paths,
        key=lambda path: hashlib.sha256(f"{seed}:{path}".encode("utf-8")).digest(),
    )


def skipped_part(value: str) -> bool:
    low = value.lower()
    return low in SKIP_PARTS or low.startswith((".venv", "venv-", "env-"))


@dataclass(frozen=True)
class CorpusRecord:
    text: str
    source: str
    category: str
    language: str
    repository: str
    path: str
    license: str

    def json(self) -> str:
        return json.dumps(asdict(self), ensure_ascii=False, separators=(",", ":"))


class CorpusBuilder:
    """Apply policy and write a reproducible, provenance-rich JSONL corpus."""

    def __init__(self, config: dict, output, *, scale: float = 1.0):
        if not 0 < scale <= 1:
            raise ValueError("scale must be in (0, 1]")
        self.config = config
        self.output = output
        self.seed = int(config["seed"])
        self.category_targets = {
            name: max(1, int(value * scale))
            for name, value in config["category_target_bytes"].items()
        }
        code_target = self.category_targets["code"]
        self.language_targets = {
            name: max(1, int(code_target * share))
            for name, share in config["code_language_shares"].items()
        }
        self.max_repo_bytes = max(
            int(config["filters"]["maximum_document_bytes"]),
            int(config["filters"]["max_repository_bytes"] * scale),
        )
        self.accepted_bytes = Counter()
        self.language_bytes = Counter()
        self.source_bytes = Counter()
        self.license_bytes = Counter()
        self.repository_bytes = Counter()
        self.accepted_documents = Counter()
        self.rejected = Counter()
        self.source_metadata: dict[str, dict] = {}
        self.seen_exact: set[str] = set()
        self.seen_normalized: set[str] = set()
        self.excluded_exact: set[str] = set()
        self.excluded_normalized: set[str] = set()

    @property
    def target_bytes(self) -> int:
        return sum(self.category_targets.values())

    @property
    def total_bytes(self) -> int:
        return sum(self.accepted_bytes.values())

    def category_remaining(self, category: str, language: str = "other") -> int:
        remaining = self.category_targets.get(category, 0) - self.accepted_bytes[category]
        if category == "code":
            normalized = normalize_language(language)
            remaining = (
                self.language_targets.get(normalized, self.language_targets.get("other", 0))
                - self.language_bytes[normalized]
            )
        return max(0, remaining)

    def _reject(self, reason: str) -> bool:
        self.rejected[reason] += 1
        return False

    def exclude_text(self, text: str) -> None:
        raw = text.encode("utf-8", errors="strict")
        normalized_text = re.sub(r"\s+", " ", text).strip().lower()
        self.excluded_exact.add(hashlib.sha256(raw).hexdigest())
        self.excluded_normalized.add(
            hashlib.sha256(normalized_text.encode("utf-8")).hexdigest()
        )

    def record_source(self, name: str, metadata: dict) -> None:
        self.source_metadata[name] = metadata

    def add(self, record: CorpusRecord) -> bool:
        category = record.category
        language = normalize_language(record.language)
        if category not in self.category_targets:
            return self._reject("unknown_category")
        text = record.text
        raw = text.encode("utf-8", errors="strict")
        size = len(raw)
        policy = self.config["filters"]
        if size < policy["minimum_document_bytes"]:
            return self._reject("too_small")
        if size > policy["maximum_document_bytes"]:
            return self._reject("too_large")
        if "\x00" in text:
            return self._reject("binary")
        path_parts = {part.lower() for part in Path(record.path).parts}
        if any(skipped_part(part) for part in path_parts) or Path(record.path).name.lower() in SKIP_NAMES:
            return self._reject("excluded_path")
        low_head = text[:4096].lower()
        if any(marker in low_head for marker in GENERATED_MARKERS):
            return self._reject("generated")
        if any(pattern.search(text) for pattern in SECRET_PATTERNS):
            return self._reject("secret")
        repository_path = f"{record.repository}/{record.path}".lower()
        if any(
            value.lower() in repository_path
            for value in policy.get("excluded_repository_substrings", [])
        ):
            return self._reject("evaluation_contamination")
        if max((len(line.encode("utf-8")) for line in text.splitlines()), default=0) > policy["maximum_line_bytes"]:
            return self._reject("long_line")
        printable = sum(character.isprintable() or character in "\n\r\t" for character in text)
        if printable / max(1, len(text)) < policy["minimum_printable_fraction"]:
            return self._reject("low_printable_fraction")
        allowed = set(self.config["allowed_licenses"])
        if record.license not in allowed:
            return self._reject("license")
        if self.repository_bytes[record.repository] + size > self.max_repo_bytes:
            return self._reject("repository_quota")
        if category != "code" and self.accepted_bytes[category] >= self.category_targets[category]:
            return self._reject("quota")
        if category == "code" and self.language_bytes[language] >= self.language_targets.get(
            language, self.language_targets.get("other", 0)
        ):
            return self._reject("quota")

        exact = hashlib.sha256(raw).hexdigest()
        normalized_text = re.sub(r"\s+", " ", text).strip().lower()
        normalized = hashlib.sha256(normalized_text.encode("utf-8")).hexdigest()
        if exact in self.excluded_exact or normalized in self.excluded_normalized:
            return self._reject("excluded_corpus_duplicate")
        if exact in self.seen_exact:
            return self._reject("exact_duplicate")
        if normalized in self.seen_normalized:
            return self._reject("normalized_duplicate")

        clean = CorpusRecord(
            text=text, source=record.source, category=category, language=language,
            repository=record.repository, path=record.path, license=record.license,
        )
        self.output.write(clean.json() + "\n")
        self.seen_exact.add(exact)
        self.seen_normalized.add(normalized)
        self.accepted_bytes[category] += size
        self.language_bytes[language] += size if category == "code" else 0
        self.source_bytes[record.source] += size
        self.license_bytes[record.license] += size
        self.repository_bytes[record.repository] += size
        self.accepted_documents[category] += 1
        return True

    def report(self, skipped_sources: list[dict] | None = None) -> dict:
        shortfall = {
            category: max(0, target - self.accepted_bytes[category])
            for category, target in self.category_targets.items()
        }
        language_shortfall = {
            language: max(0, target - self.language_bytes[language])
            for language, target in self.language_targets.items()
        }
        return {
            "format": "brittain3-tokenizer-corpus-report-v1",
            "config_sha256": hashlib.sha256(
                json.dumps(self.config, sort_keys=True, separators=(",", ":")).encode("utf-8")
            ).hexdigest(),
            "seed": self.seed,
            "target_bytes": self.target_bytes,
            "accepted_bytes": self.total_bytes,
            "complete": not any(shortfall.values()) and not any(language_shortfall.values()),
            "category_target_bytes": self.category_targets,
            "category_accepted_bytes": dict(self.accepted_bytes),
            "category_shortfall_bytes": shortfall,
            "code_language_target_bytes": self.language_targets,
            "code_language_accepted_bytes": dict(self.language_bytes),
            "code_language_shortfall_bytes": language_shortfall,
            "source_bytes": dict(self.source_bytes),
            "license_bytes": dict(self.license_bytes),
            "accepted_documents": dict(self.accepted_documents),
            "rejected_documents": dict(self.rejected),
            "repositories": len(self.repository_bytes),
            "source_metadata": self.source_metadata,
            "skipped_sources": skipped_sources or [],
        }


def iter_local_repository(
    root: str | Path,
    *,
    source: str,
    license_name: str,
    seed: int,
) -> Iterator[CorpusRecord]:
    base = Path(root).expanduser().resolve()
    if not base.is_dir():
        raise ValueError(f"local repository does not exist: {base}")
    paths = []
    for directory, directories, filenames in os.walk(base):
        directories[:] = [name for name in directories if not skipped_part(name)]
        for filename in filenames:
            path = Path(directory) / filename
            relative = path.relative_to(base)
            category, _ = classify_path(str(relative))
            if category is not None and filename.lower() not in SKIP_NAMES:
                paths.append(path)
    for path in stable_order(paths, seed):
        relative = path.relative_to(base)
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        yield CorpusRecord(
            text=text,
            source=source,
            category=classify_path(str(relative))[0] or "code",
            language=classify_path(str(relative))[1],
            repository=base.name,
            path=str(relative),
            license=license_name,
        )


def tool_records(paths: Iterable[str | Path], seed: int) -> Iterator[CorpusRecord]:
    """Yield raw tool sources and varied, valid JSON tool-call examples."""
    names = set()
    raw_documents = []
    for value in paths:
        path = Path(value).expanduser().resolve()
        if not path.is_file():
            continue
        text = path.read_text(encoding="utf-8", errors="strict")
        raw_documents.append((path, text))
        names.update(re.findall(r"\bname\s*:\s*['\"]([A-Za-z_][A-Za-z0-9_]*)['\"]", text))
        names.update(re.findall(r'"name"\s*:\s*"([A-Za-z_][A-Za-z0-9_]*)"', text))
    for path, text in raw_documents:
        yield CorpusRecord(
            text=text, source="brittain_tools", category="tool", language="other",
            repository="brittain-code", path=path.name, license="OWNED",
        )

    rng = random.Random(seed)
    paths_pool = ["src/app.js", "src/tools/policy.js", "tests/test_api.py", "README.md"]
    symbols = ["parseConfig", "runCommand", "Brittain3", "applyPatch"]
    for index in range(768):
        for name in sorted(names):
            path = rng.choice(paths_pool)
            symbol = rng.choice(symbols)
            arguments = {"path": path}
            if "search" in name:
                arguments = {"pattern": symbol, "path": "src"}
            elif "symbol" in name or "reference" in name:
                arguments = {"name": symbol, "path": "src"}
            elif "command" in name or "check" in name:
                arguments = {"command": "python3 -m pytest -q"}
            call = json.dumps({"name": name, "arguments": arguments}, ensure_ascii=False)
            result = json.dumps({
                "ok": True, "path": path, "matches": index % 4,
                "request_id": f"tool-{index:04d}",
            })
            text = (
                "<|user|>Inspect the project and continue the coding task.<|end_message|>"
                f"<|assistant|><|tool_call|>{call}<|end_message|>"
                f"<|tool_result|>{result}<|end_message|>"
                f"<|assistant|>I inspected {path} and found {symbol}.<|end_message|>"
            )
            yield CorpusRecord(
                text=text, source="brittain_tools_synthetic", category="tool",
                language="other", repository="brittain-code",
                path=f"synthetic/{name}/{index}.json", license="OWNED",
            )
